image: node:latest

stages:
  - build
  - test
  - publish

cache:
  paths:
    - node_modules/
    - dist/

build:
  stage: "build"
  script:
    - "npm i"
    - "npm run build"

test:
  stage: "test"
  script:
   - "npm i"
   - "npm run test"

publish:
  stage: "publish"
  only:
    - main
  script:
   - "npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}"
   - "npm run dopublish"